server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/med
    username: root
    password: med
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: false # Disable Flyway for now

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    sql:
      init:
        mode: always

  h2:
    console:
      enabled: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  security:
    user:
      name: user
      password: password
    default:
      enabled: false

logging:
  level:
    root: info
    org.springframework.web: debug


jwt:
  secret: 2KECiXj8IGx/Vfvnpqe8LXTwbPbNlyPACaazXGzI458=
#  access-token-expiration: 3600000 # 1 hour
#  refresh-token-expiration: 86400000 # 1 day
#  access-token-expiration: 60000 # 1 minute in milliseconds
#  refresh-token-expiration: 300000 # 5 minutes in milliseconds
  access-token-expiration: 604800000 # 1 week in milliseconds
  refresh-token-expiration: 2592000000 # 1 month in milliseconds

springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha