server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-db
    username: med
    password: med
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    password: med
    user: med
    baseline-description: "initial schema"
    baseline-version: 1

  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: true
      use_sql_comments: true
      show_sql: true
    properties:
      hibernate:
        multiTenancy: SCHEMA
    sql:
      init:
        mode: always

  h2:
    console:
      enabled: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  security:
    user:
      name: user
      password: password
    default:
      enabled: false
  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    root: info
    org.springframework.web: debug
    org.flywaydb: DEBUG


jwt:
  secret: 2KECiXj8IGx/Vfvnpqe8LXTwbPbNlyPACaazXGzI458=
  access-token-expiration: 604800000 # 1 week in milliseconds
  refresh-token-expiration: 2592000000 # 1 month in milliseconds

springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha
file:
  images-folder-path: uploads/


