version: '3.8'

services:
  # PostgreSQL database service
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: med
      POSTGRES_PASSWORD: med
      POSTGRES_DB: med
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network
networks:
  postgres-network:

volumes:
  db_data:
